#!/usr/bin/env sh
set -e

echo "Running OpenAPI generation before push..."
pnpm generate:openapi

if ! git diff --quiet mintlify/openapi/openapi.json; then
  echo "OpenAPI changed. Amending last commit..."

  git add mintlify/openapi/openapi.json
  git commit --amend --no-edit
fi

echo "OpenAPI is up-to-date. Proceeding with push."